## Petrol Stations Project : Data Preprocessing

---
This notebook focuses on the data preprocessing steps. The goal is to clean and prepare the dataset for subsequent analysis and modeling, ensuring that the data is in a suitable format for machine learning algorithms.

**Author:**
 👨‍💻    [Anabel Díaz](https://github.com/rubiwan)

## Initial Data Exploration
---
### 1. Understanding the dataset
- Dataset loading into a pandas DataFrame.
- Display structure and content.

In [1]:
import pandas as pd

df = pd.read_csv("gii32_ act1_precios_carburantes_24.csv")
df.head()

,Provincia,Municipio,Localidad,Código postal,Dirección,Precio gasolina 95 E5,Precio gasóleo A,Tipo venta,Tipo servicio,Rótulo
0,ALBACETE,ABENGIBRE,ABENGIBRE,2250,"AVENIDA CASTILLA LA MANCHA, 26","1,529","1,419",P,A,Nº 10.935
1,ALBACETE,ALBACETE,ALBACETE,2001,"CALLE FEDERICO GARCIA LORCA, 5",NaN,"1,560",R,A,CEPSA
2,ALBACETE,ALBACETE,ALBACETE,2001,"CALLE FEDERICO GARCIA LORCA, 1","1,409","1,399",P,D,PLENOIL
3,ALBACETE,ALBACETE,ALBACETE,2001,"AVENIDA 1º DE MAYO, S/N","1,539","1,489",P,A,CARREFOUR
4,ALBACETE,ALBACETE,ALBACETE,2001,CALLE PRINCIPE DE ASTURIAS (POLÍGONO DE ROMICA...,"1,549","1,549",P,A,BP ROMICA

### 2. Number of rows and columns
- Explore the dataset to understand its structure and dimensions.
- This is fundamental for planning the analysis and data preprocessing steps.

In [2]:
df.shape

(11865, 10)

### 3. Column names
- Review the column names for a better understanding of the data
- Identify any potential issues with naming conventions that may need to be addressed during preprocessing.

In [3]:
df.columns

Index(['Provincia', 'Municipio', 'Localidad', 'Código postal', 'Dirección',
       'Precio gasolina 95 E5', 'Precio gasóleo A', 'Tipo venta',
       'Tipo servicio', 'Rótulo'],
      dtype='object')

### 4. Missing values and data types
- Check for missing values in the dataset to identify any gaps in the data that may need to be addressed.
- Review the data types of each column to ensure they are appropriate for analysis and modeling.

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11865 entries, 0 to 11864
Data columns (total 10 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Provincia              11865 non-null  object
 1   Municipio              11865 non-null  object
 2   Localidad              11865 non-null  object
 3   Código postal          11865 non-null  int64
 4   Dirección              11865 non-null  object
 5   Precio gasolina 95 E5  10702 non-null  object
 6   Precio gasóleo A       11498 non-null  object
 7   Tipo venta             11865 non-null  object
 8   Tipo servicio          10803 non-null  object
 9   Rótulo                 11865 non-null  object
dtypes: int64(1), object(9)
memory usage: 927.1+ KB

## Data Preprocessing
---
### 5. Statical summary.
- Correct understanding the distribution and characteristics of the data, which can inform subsequent preprocessing and analysis steps.

In [5]:
df.describe(include='all')

,Provincia,Municipio,Localidad,Código postal,Dirección,Precio gasolina 95 E5,Precio gasóleo A,Tipo venta,Tipo servicio,Rótulo
count,11865,11865,11865,11865.000000,11865,10702,11498,11865,10803,11865
unique,52,3415,4228,NaN,11554,414,438,3,3,4025
top,MADRID,MADRID,MADRID,NaN,"AVENIDA ANDALUCIA, S/N","1,559","1,569",P,A,REPSOL
freq,852,241,241,NaN,11,568,642,11105,8098,2733
mean,NaN,NaN,NaN,25413.898272,NaN,NaN,NaN,NaN,NaN,NaN
std,NaN,NaN,NaN,14476.124512,NaN,NaN,NaN,NaN,NaN,NaN
min,NaN,NaN,NaN,1002.000000,NaN,NaN,NaN,NaN,NaN,NaN
25%,NaN,NaN,NaN,12006.000000,NaN,NaN,NaN,NaN,NaN,NaN
50%,NaN,NaN,NaN,27246.000000,NaN,NaN,NaN,NaN,NaN,NaN
75%,NaN,NaN,NaN,38002.000000,NaN,NaN,NaN,NaN,NaN,NaN
max,NaN,NaN,NaN,52006.000000,NaN,NaN,NaN,NaN,NaN,NaN

### 5. Filter by column.
- Filter the dataset to include only rows where the "Provincia" column has the value "Madrid". This allows us to focus our analysis on a specific region, which can be useful for understanding local trends and patterns in petrol prices.